# This database was created using the openai prompt found in example city preference.py file
city_data = {
    "Abu Dhabi, United Arab Emirates": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": True,
        "Shellfish": False,
        "Nuts": False,
        "halaal": True,
        "Walkable": True,
        "region": [False, False, False, True, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Accra, Ghana": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Ahmedabad, India": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": True,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": False,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, True, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Aguascalientes, Mexico": {
        "hot": True,
        "cold": False,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Albany, New York": {
        "hot": False,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [True, False, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": False,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Albuquerque, New Mexico": {
        "hot": True,
        "cold": False,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Alexandria, Louisiana": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Allentown, Pennsylvania": {
        "hot": False,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [True, False, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": False,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Amman, Jordan": {
        "hot": True,
        "cold": False,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Amsterdam, Netherlands": {
        "hot": False,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": True,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Anchorage, Alaska": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, False, False, True],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, True],
        "kid_friendly": True,
        "nightlife": True
    },
    "Antigua, Antigua and Barbuda": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, True, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Appleton, Wisconsin": {
        "hot": True,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Aruba, Aruba": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, True, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Asheville, North Carolina": {
        "hot": True,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Athens, Greece": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Atlanta, Georgia": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Auckland, New Zealand": {
        "hot": False,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, True],
        "kid_friendly": True,
        "nightlife": True
    },
    "Austin, Texas": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Baltimore, Maryland": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Barcelona, Spain": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Barranquilla, Colombia": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, True, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Beijing, China": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Belfast, Northern Ireland": {
        "hot": False,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [True, False, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Belize City, Belize": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": True,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Bentonville, Arkansas": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Berlin, Germany": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, True, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Bermuda, Bermuda": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, True, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Birmingham, Alabama": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, True, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Birmingham, England": {
        "hot": False,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [True, False, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Bismarck, North Dakota": {
        "hot": False,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [True, False, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Boise, Idaho": {
        "hot": True,
        "cold": False,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Bologna, Italy": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Boston, Massachusetts": {
        "hot": False,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [True, False, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": False,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Bozeman, Montana": {
        "hot": False,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [True, False, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": False,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Brasilia, Brazil": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, True],
        "kid_friendly": True,
        "nightlife": True
    },
    "Bridgetown, Barbados": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, True, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Brussels, Belgium": {
        "hot": False,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Bucharest, Romania": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Buffalo, New York": {
        "hot": False,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [True, False, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": False,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Burlington, Vermont": {
        "hot": False,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [True, False, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": False,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Calgary, Alberta": {
        "hot": False,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [True, False, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": False,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Cancún, Mexico": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Cape Town, South Africa": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, True, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Caracas, Venezuela": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, True, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Cartagena, Colombia": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, True, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Casablanca, Morocco": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": False,
        "halaal": True,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Charleston, South Carolina": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [True, False, False, False, False, False, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Charlotte, North Carolina": {
        "hot": True,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Chattanooga, Tennessee": {
        "hot": True,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": False,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Chennai, India": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": False,
        "halaal": True,
        "Walkable": True,
        "region": [False, False, False, True, False, False, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Chicago, Illinois": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [True, False, False, True],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Chihuahua, Mexico": {
        "hot": True,
        "cold": True,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": False,
        "halaal": True,
        "Walkable": True,
        "region": [False, False, False, False, False, False, True],
        "kid friendly": True,
        "nightlife": True,
    },
    "Cincinnati, Ohio": {
        "hot": True,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": False,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Cleveland, Ohio": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [True, False, False, True],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Colorado Springs, Colorado": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": False,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Columbus, Ohio": {
        "hot": True,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": False,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Cozumel, Mexico": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": False,
        "halaal": True,
        "Walkable": True,
        "region": [False, False, False, False, False, False, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Curaçao, Curaçao": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, True, False, False, False, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Dallas, Texas": {
        "hot": True,
        "cold": True,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": False,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Dayton, Ohio": {
        "hot": True,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": False,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Delhi, India": {
        "hot": True,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": False,
        "halaal": True,
        "Walkable": True,
        "region": [False, False, False, True, False, False, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Denver, Colorado": {
        "hot": True,
        "cold": True,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": False,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Des Moines, Iowa": {
        "hot": True,
        "cold": True,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": False,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Detroit, Michigan": {
        "hot": True,
        "cold": True,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": False,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Doha, Qatar": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": True,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": True,
        "Walkable": True,
        "region": [False, False, False, False, False, False, True],
        "kid friendly": True,
        "nightlife": True,
    },
    "Dublin, Ireland": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [True, False, False, True],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid friendly": True,
        "nightlife": True,
    },
    "Durango, Mexico": {
        "hot": True,
        "cold": True,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": False,
        "halaal": True,
        "Walkable": True,
        "region": [False, False, False, False, False, False, True],
        "kid friendly": True,
        "nightlife": True,
    },
    "Düsseldorf, Germany": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [True, False, False, True],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, True],
        "kid friendly": True,
        "nightlife": True,
    },
    "Edinburgh, Scotland": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [True, False, False, True],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
    },
    "Edmonton, Alberta": {
        "hot": True,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [True, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "El Paso, Texas": {
        "hot": True,
        "cold": False,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, True, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [True, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Fairbanks, Alaska": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, False, True],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Faro, Portugal": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, True, True],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Fortaleza, Brazil": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, True, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Frankfurt, Germany": {
        "hot": True,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Fresno, California": {
        "hot": True,
        "cold": False,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, True, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [True, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Geneva, Switzerland": {
        "hot": True,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Glasgow, Scotland": {
        "hot": False,
        "cold": True,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Gothenburg, Sweden": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Grand Cayman, Cayman Islands": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, True],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, True, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Grand Rapids, Michigan": {
        "hot": True,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [True, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Greensboro, North Carolina": {
        "hot": True,
        "cold": False,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, True, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [True, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Guadalajara, Mexico": {
        "hot": True,
        "cold": False,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, True, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [True, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Guatemala City, Guatemala": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, True, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Guayaquil, Ecuador": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, True, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Gulfport, Mississippi": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [True, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Halifax, Nova Scotia": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [True, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Hamburg, Germany": {
        "hot": True,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Hamilton, Bermuda": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, True],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Hannover, Germany": {
        "hot": True,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Harlingen, Texas": {
        "hot": True,
        "cold": False,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, True, True, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [True, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Hartford, Connecticut": {
        "hot": True,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": True,
        "Gluten": True,
        "Shellfish": True,
        "Nuts": True,
        "halaal": False,
        "Walkable": True,
        "region": [True, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": True
    },
    "Helsinki, Finland": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, False, True],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Hermosillo, Mexico": {
        "hot": True,
        "cold": False,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": True,
        "Walkable": False,
        "region": [False, True, False, False, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Hilo, Hawaii": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [True, False, False, False, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Hobart, Tasmania": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, False, True],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Hong Kong, Hong Kong": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [False, False, False, True, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Honolulu, Hawaii": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [True, False, False, False, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Houston, Texas": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Huntsville, Alabama": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": True,
        "nightlife": False
    },
    "Indianapolis, Indiana": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, False, True],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [False, False, False, False, True, False, False],
        "kid_friendly": True,
        "nightlife": False
    },
    "Ixtapa/Zihuatanejo, Mexico": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": True,
        "Walkable": False,
        "region": [False, True, False, False, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Jackson, Mississippi": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Jacksonville, Florida": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Jamaica, Jamaica": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Jeddah, Saudi Arabia": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": True,
        "Walkable": False,
        "region": [False, False, False, True, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Johannesburg, South Africa": {
        "hot": True,
        "cold": False,
        "humid": False,
        "dry": True,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [False, False, False, False, False, False, True],
        "kid_friendly": False,
        "nightlife": False
    },
    "Kahului, Hawaii": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [True, False, False, False, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Kailua-Kona, Hawaii": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [True, False, False, False, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Kansas City, Missouri": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, False, True],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": False,
        "nightlife": True
    },
    "Kathmandu, Nepal": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, True, False, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [False, False, False, True, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Kingston, Jamaica": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Knoxville, Tennessee": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [False, False, False, False, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Kona, Hawaii": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [True, False, False, False, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Kraków, Poland": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, False, True],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": True,
        "region": [False, False, False, False, False, True, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Kuala Lumpur, Malaysia": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [False, False, False, True, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "Kuwait City, Kuwait": {
        "hot": True,
        "cold": False,
        "humid": True,
        "dry": True,
        "best_time_of_year_to_visit": [False, False, True, False],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": True,
        "Walkable": False,
        "region": [False, False, False, True, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
    "La Paz, Bolivia": {
        "hot": False,
        "cold": True,
        "humid": False,
        "dry": False,
        "best_time_of_year_to_visit": [False, False, False, True],
        "Dairy": False,
        "Gluten": False,
        "Shellfish": False,
        "Nuts": False,
        "halaal": False,
        "Walkable": False,
        "region": [False, True, False, False, False, False, False],
        "kid_friendly": False,
        "nightlife": False
    },
}